In [27]:
from einops import rearrange, einsum, pack
import torch
import math
from utils import init_custom_weight, inspect_tensor
from tokenizerModule import ID_mapper


In [2]:
x = torch.empty(3,4)
init_custom_weight(x, is_residual_output=False)
inspect_tensor(x, name="Linear_Proj_Weight", category="weight").print_summary()


=== Linear_Proj_Weight [WEIGHT] Status: HEALTHY ===
Metrics:
  - numel: 12
  - mean: 3.771693e-03
  - std: 1.551946e-02
  - var: 2.408537e-04
  - min: -2.801843e-02
  - max: 3.615297e-02
  - l2_norm: 5.532587e-02
  - zero_fraction: 0.000000e+00
  - nan_count: 0
  - inf_count: 0
  - outlier_ratio_3sigma: 0.000000e+00



In [3]:
# powers of 2 
for i in range(15):
    print(f"2**{i} = {2**i}")

2**0 = 1
2**1 = 2
2**2 = 4
2**3 = 8
2**4 = 16
2**5 = 32
2**6 = 64
2**7 = 128
2**8 = 256
2**9 = 512
2**10 = 1024
2**11 = 2048
2**12 = 4096
2**13 = 8192
2**14 = 16384


In [4]:
from tokenizerModule import Tokenizer


prompt_to_IDs = Tokenizer.encode("hello, how are you?")

# torch tensor
# x = torch.tensor(prompt_to_IDs).unsqueeze(0)  # Add batch dimension

# x = torch.tensor()


# print(x)

ImportError: cannot import name 'Tokenizer' from 'tokenizerModule' (c:\Users\raman sh\Desktop\From Matrix to Mind\code\tokenizerModule.py)

In [ ]:
import training_engine as training_engine

loader = training_engine.BatchLoader(train = True, batch_size=1, max_seq_len=12, device='cuda')
x, y = loader.get_batch()
print(x)
print("-"*80)
print(y)


tensor([[ 102, 1989,  564, 1082,  526,  291,  172,  352,  715,  553,  679,   97]],
       device='cuda:0')
--------------------------------------------------------------------------------
tensor([[1989,  564, 1082,  526,  291,  172,  352,  715,  553,  679,   97,  545]],
       device='cuda:0')


In [ ]:
# fixed sinusoidal positional encodings

position = torch.arange(0, 64, dtype=torch.float).unsqueeze(1) # Shape: (max_seq_len, 1)
# print(position)

sini = torch.sin(position*2)
# print(sini)

# position[1::2]


# Geometric progression division term: 10000^(2i/d_embed)
div_term = torch.exp(torch.arange(0, 32, step=2).float() *
                        (-math.log(10000.0) / 32)
                    ) # Shape: (embed_dim/2)

# div_term.shape
# torch.arange(0, 32, step=2).float().shape
# -math.log(10000.0) /32
torch.exp(torch.arange(0, 32, step=2)) # 1.0686e+13
torch.exp(torch.tensor([30]))

tensor([1.0686e+13])

In [ ]:
w = torch.randn(3,(2*2))
x = torch.randn(1,3)

# y = einsum(x,w, "b d, i o -> b o")
y = einsum(x,w, "b d, i o "
                "-> "
                "b o"
                )
y

tensor([[-0.3964, -3.2323, -1.5661, -4.8307]])

In [12]:
x = torch.tensor([[1430,  787,  138,  379,   68,  264,   52,  395],
        [1430,  787, 1776, 1574,  225,  198,  398, 1115],
        [1430,  787, 1776, 1574,  225,  198,  398, 1115]])

seq = x

xx = torch.tensor([[225],[787],[1776]]) # [3,1]
seq, dim = pack([seq, xx], "batch_size *")
seq.shape


torch.Size([3, 9])

In [ ]:
# einops



In [26]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
print(torch.cuda.get_device_capability())
print(torch.backends.cuda.is_flash_attention_available())


(7, 5)
False
