In [14]:
import torch
import math

In [2]:
# powers of 2 
for i in range(15):
    print(f"2**{i} = {2**i}")

2**0 = 1
2**1 = 2
2**2 = 4
2**3 = 8
2**4 = 16
2**5 = 32
2**6 = 64
2**7 = 128
2**8 = 256
2**9 = 512
2**10 = 1024
2**11 = 2048
2**12 = 4096
2**13 = 8192
2**14 = 16384


In [5]:
from tokenizerModule import Tokenizer


prompt_to_IDs = Tokenizer.encode("hello, how are you?")

# torch tensor
# x = torch.tensor(prompt_to_IDs).unsqueeze(0)  # Add batch dimension

# x = torch.tensor()


# print(x)

In [ ]:
import training_engine as training_engine

loader = training_engine.BatchLoader(train = True, batch_size=1, max_seq_len=12, device='cuda')
x, y = loader.get_batch()
print(x)
print("-"*80)
print(y)


tensor([[ 102, 1989,  564, 1082,  526,  291,  172,  352,  715,  553,  679,   97]],
       device='cuda:0')
--------------------------------------------------------------------------------
tensor([[1989,  564, 1082,  526,  291,  172,  352,  715,  553,  679,   97,  545]],
       device='cuda:0')


In [30]:
# fixed sinusoidal positional encodings

position = torch.arange(0, 64, dtype=torch.float).unsqueeze(1) # Shape: (max_seq_len, 1)
# print(position)

sini = torch.sin(position*2)
# print(sini)

# position[1::2]


# Geometric progression division term: 10000^(2i/d_embed)
div_term = torch.exp(torch.arange(0, 32, step=2).float() *
                        (-math.log(10000.0) / 32)
                    ) # Shape: (embed_dim/2)

# div_term.shape
# torch.arange(0, 32, step=2).float().shape
# -math.log(10000.0) /32
torch.exp(torch.arange(0, 32, step=2)) # 1.0686e+13
torch.exp(torch.tensor([30]))

tensor([1.0686e+13])